### ISSUE TITLE
sentences2.csv makhdamch 

### ISSUE THREAD

**Issue by Strifee** [darija-open-dataset/dataset#28]
bghit ndir had dataset f dataframe w kaitl3o li had l error
---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
<ipython-input-84-591d9c727c39> in <module>
      1 import pandas as pd
      2 
----> 3 print(pd.read_csv("dataset/sentences2.csv"))

~\anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    452 
    453     try:
--> 454         data = parser.read(nrows)
    455     finally:
    456         parser.close()

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   1131     def read(self, nrows=None):
   1132         nrows = _validate_integer("nrows", nrows)
-> 1133         ret = self._engine.read(nrows)
   1134 
   1135         # May alter columns / col_dict

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   2035     def read(self, nrows=None):
   2036         try:
-> 2037             data = self._reader.read(nrows)
   2038         except StopIteration:
   2039             if self._first_chunk:

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 2 fields in line 1865, saw 4
-------------------------------------------------------------------------------
o fach kandir rror_bad_lines=False kaitl3lya hdchi

![Capture d’écran 2021-05-07 162904](https://user-images.githubusercontent.com/63970317/117480610-5ba9d280-af51-11eb-869f-ab40110b674f.png)

**Comment by Strifee** [comment]
https://csvlint.io/validation/60956b17ce9e5f000400004e

probleme mn csv file 

![image](https://user-images.githubusercontent.com/63970317/117480860-adeaf380-af51-11eb-94c3-d403aac8d093.png)

**Comment by darija-open-dataset** [comment]
salam, merci pour la remarque.
Oui il y a avait un problème de "quotation marks", daba tu peux tester rah mziane
Je note aussi que le fichier est en cours de remplissage donc kolla nhar tanzidou chwia :) (yalah 3amr fih 285 lignes daba), il y a aussi **sentences.csv** fih chi haja b7al hakka ..

**Comment by Strifee** [comment]
ok chokran bzaf
