### ISSUE TITLE
Hosting the dataset on DataStack?

### ISSUE THREAD

**Issue by boukeversteegh** [darija-open-dataset/dataset#60]
Hello!

I enjoy seeing community data projects like this. As a former student of Cantonese (a dialect of Chinese spoken in HongKong), I know what it's like when the language you're interested in has no dictionary. At one point, I tried to create one myself, but gave up after 500 words. It's too much effort to do it alone.

The issue today is, that working together on these things is very technical. I'm sure your contributors here are familiar with Github and have no problem helping out, but it would be great if anyone with just the knowledge of English and Darija could help out, without technical skills.

For this reason I am building DataStack. It's a collaboration platform for table data, and works similarly to Github, but much more easy to use for data. No tools or technical knowledge needed.

To show you what it looks like, I've uploaded two files from your dataset there:

- https://datastack.net/boukeversteegh/darija-open-dataset-demo/

If you're interested, please have a look. Does this solution suit your needs? What is still missing in your opinion?

**Comment by aissam-out** [comment]
Yeah, we'd like to :) it's a well designed & handy platform. I'll take a look at it later this week. Thanks for opening this issue :)

**Comment by boukeversteegh** [comment]
Great, with pleasure! When you're ready, drop me an email at info@datastack.net or [sign up](https://blog.datastack.net/subscribe/) so I can invite you to the beta.
